-- Adds 50 more characters and their evolution paths.
-- This is a migration (not a seed) so the production deploy workflow applies it.
-- Pikachu, Gengar, Lucario and Snorlax are evolution targets from 001_demo.sql;
-- they are inserted here too so this works on a database that was never seeded.
-- INSERT OR IGNORE leaves any existing rows untouched.
-- Each character has at most one outgoing evolution path because the collection
-- and evolve queries assume a single path, so Eeveelutions are shop items.

INSERT OR IGNORE INTO characters (id, external_id, name, slug, type_primary, type_secondary, image_url, price, rarity) VALUES
  ('char_pikachu', '25', 'Pikachu', 'pikachu', 'Electric', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png', 500, 'RARE'),
  ('char_snorlax', '143', 'Snorlax', 'snorlax', 'Normal', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png', 800, 'RARE'),
  ('char_gengar', '94', 'Gengar', 'gengar', 'Ghost', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png', 900, 'EPIC'),
  ('char_lucario', '448', 'Lucario', 'lucario', 'Fighting', 'Steel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/448.png', 1000, 'EPIC');

INSERT OR IGNORE INTO characters (id, external_id, name, slug, type_primary, type_secondary, image_url, price, rarity) VALUES
  ('char_caterpie', '10', 'Caterpie', 'caterpie', 'Bug', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png', 300, 'COMMON'),
  ('char_metapod', '11', 'Metapod', 'metapod', 'Bug', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/11.png', 0, 'RARE'),
  ('char_butterfree', '12', 'Butterfree', 'butterfree', 'Bug', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/12.png', 0, 'EPIC'),
  ('char_pidgey', '16', 'Pidgey', 'pidgey', 'Normal', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/16.png', 300, 'COMMON'),
  ('char_pidgeotto', '17', 'Pidgeotto', 'pidgeotto', 'Normal', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/17.png', 0, 'RARE'),
  ('char_pidgeot', '18', 'Pidgeot', 'pidgeot', 'Normal', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/18.png', 0, 'EPIC'),
  ('char_pichu', '172', 'Pichu', 'pichu', 'Electric', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/172.png', 300, 'COMMON'),
  ('char_jigglypuff', '39', 'Jigglypuff', 'jigglypuff', 'Normal', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/39.png', 350, 'COMMON'),
  ('char_wigglytuff', '40', 'Wigglytuff', 'wigglytuff', 'Normal', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/40.png', 0, 'RARE'),
  ('char_vulpix', '37', 'Vulpix', 'vulpix', 'Fire', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/37.png', 400, 'COMMON'),
  ('char_ninetales', '38', 'Ninetales', 'ninetales', 'Fire', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/38.png', 0, 'EPIC'),
  ('char_meowth', '52', 'Meowth', 'meowth', 'Normal', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/52.png', 350, 'COMMON'),
  ('char_persian', '53', 'Persian', 'persian', 'Normal', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/53.png', 0, 'RARE'),
  ('char_psyduck', '54', 'Psyduck', 'psyduck', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/54.png', 350, 'COMMON'),
  ('char_golduck', '55', 'Golduck', 'golduck', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/55.png', 0, 'RARE'),
  ('char_growlithe', '58', 'Growlithe', 'growlithe', 'Fire', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/58.png', 450, 'COMMON'),
  ('char_arcanine', '59', 'Arcanine', 'arcanine', 'Fire', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/59.png', 0, 'EPIC'),
  ('char_abra', '63', 'Abra', 'abra', 'Psychic', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/63.png', 400, 'COMMON'),
  ('char_kadabra', '64', 'Kadabra', 'kadabra', 'Psychic', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/64.png', 0, 'RARE'),
  ('char_alakazam', '65', 'Alakazam', 'alakazam', 'Psychic', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/65.png', 0, 'EPIC'),
  ('char_machop', '66', 'Machop', 'machop', 'Fighting', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/66.png', 400, 'COMMON'),
  ('char_machoke', '67', 'Machoke', 'machoke', 'Fighting', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/67.png', 0, 'RARE'),
  ('char_machamp', '68', 'Machamp', 'machamp', 'Fighting', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/68.png', 0, 'EPIC'),
  ('char_geodude', '74', 'Geodude', 'geodude', 'Rock', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/74.png', 350, 'COMMON'),
  ('char_graveler', '75', 'Graveler', 'graveler', 'Rock', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/75.png', 0, 'RARE'),
  ('char_golem', '76', 'Golem', 'golem', 'Rock', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/76.png', 0, 'EPIC'),
  ('char_gastly', '92', 'Gastly', 'gastly', 'Ghost', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/92.png', 450, 'COMMON'),
  ('char_haunter', '93', 'Haunter', 'haunter', 'Ghost', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/93.png', 0, 'RARE'),
  ('char_magikarp', '129', 'Magikarp', 'magikarp', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/129.png', 150, 'COMMON'),
  ('char_gyarados', '130', 'Gyarados', 'gyarados', 'Water', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png', 0, 'EPIC'),
  ('char_dratini', '147', 'Dratini', 'dratini', 'Dragon', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/147.png', 600, 'RARE'),
  ('char_dragonair', '148', 'Dragonair', 'dragonair', 'Dragon', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/148.png', 0, 'EPIC'),
  ('char_dragonite', '149', 'Dragonite', 'dragonite', 'Dragon', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png', 0, 'LEGENDARY'),
  ('char_riolu', '447', 'Riolu', 'riolu', 'Fighting', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/447.png', 500, 'RARE'),
  ('char_munchlax', '446', 'Munchlax', 'munchlax', 'Normal', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/446.png', 400, 'COMMON'),
  ('char_vaporeon', '134', 'Vaporeon', 'vaporeon', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/134.png', 900, 'EPIC'),
  ('char_jolteon', '135', 'Jolteon', 'jolteon', 'Electric', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/135.png', 900, 'EPIC'),
  ('char_flareon', '136', 'Flareon', 'flareon', 'Fire', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/136.png', 900, 'EPIC'),
  ('char_espeon', '196', 'Espeon', 'espeon', 'Psychic', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/196.png', 950, 'EPIC'),
  ('char_umbreon', '197', 'Umbreon', 'umbreon', 'Dark', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/197.png', 950, 'EPIC'),
  ('char_leafeon', '470', 'Leafeon', 'leafeon', 'Grass', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/470.png', 950, 'EPIC'),
  ('char_glaceon', '471', 'Glaceon', 'glaceon', 'Ice', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/471.png', 950, 'EPIC'),
  ('char_sylveon', '700', 'Sylveon', 'sylveon', 'Fairy', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/700.png', 1000, 'EPIC'),
  ('char_lapras', '131', 'Lapras', 'lapras', 'Water', 'Ice', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/131.png', 900, 'RARE'),
  ('char_ditto', '132', 'Ditto', 'ditto', 'Normal', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/132.png', 700, 'RARE'),
  ('char_articuno', '144', 'Articuno', 'articuno', 'Ice', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/144.png', 2000, 'LEGENDARY'),
  ('char_zapdos', '145', 'Zapdos', 'zapdos', 'Electric', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/145.png', 2000, 'LEGENDARY'),
  ('char_moltres', '146', 'Moltres', 'moltres', 'Fire', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/146.png', 2000, 'LEGENDARY'),
  ('char_mewtwo', '150', 'Mewtwo', 'mewtwo', 'Psychic', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png', 3000, 'LEGENDARY'),
  ('char_mew', '151', 'Mew', 'mew', 'Psychic', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/151.png', 3000, 'LEGENDARY');

INSERT OR IGNORE INTO evolution_paths (id, from_character_id, to_character_id, point_cost) VALUES
  ('evo_caterpie_metapod', 'char_caterpie', 'char_metapod', 600),
  ('evo_metapod_butterfree', 'char_metapod', 'char_butterfree', 1000),
  ('evo_pidgey_pidgeotto', 'char_pidgey', 'char_pidgeotto', 600),
  ('evo_pidgeotto_pidgeot', 'char_pidgeotto', 'char_pidgeot', 1000),
  ('evo_pichu_pikachu', 'char_pichu', 'char_pikachu', 400),
  ('evo_jigglypuff_wigglytuff', 'char_jigglypuff', 'char_wigglytuff', 800),
  ('evo_vulpix_ninetales', 'char_vulpix', 'char_ninetales', 800),
  ('evo_meowth_persian', 'char_meowth', 'char_persian', 800),
  ('evo_psyduck_golduck', 'char_psyduck', 'char_golduck', 800),
  ('evo_growlithe_arcanine', 'char_growlithe', 'char_arcanine', 1000),
  ('evo_abra_kadabra', 'char_abra', 'char_kadabra', 600),
  ('evo_kadabra_alakazam', 'char_kadabra', 'char_alakazam', 1000),
  ('evo_machop_machoke', 'char_machop', 'char_machoke', 600),
  ('evo_machoke_machamp', 'char_machoke', 'char_machamp', 1000),
  ('evo_geodude_graveler', 'char_geodude', 'char_graveler', 600),
  ('evo_graveler_golem', 'char_graveler', 'char_golem', 1000),
  ('evo_gastly_haunter', 'char_gastly', 'char_haunter', 600),
  ('evo_haunter_gengar', 'char_haunter', 'char_gengar', 1000),
  ('evo_magikarp_gyarados', 'char_magikarp', 'char_gyarados', 1200),
  ('evo_dratini_dragonair', 'char_dratini', 'char_dragonair', 1000),
  ('evo_dragonair_dragonite', 'char_dragonair', 'char_dragonite', 1500),
  ('evo_riolu_lucario', 'char_riolu', 'char_lucario', 800),
  ('evo_munchlax_snorlax', 'char_munchlax', 'char_snorlax', 600);
