-- Adds 60 more characters: seven starter lines (Hoenn to Alola), five pseudo-legendary
-- lines (Tyranitar, Salamence, Metagross, Garchomp, Haxorus), more three- and two-stage
-- lines, and five shop legendaries. Base forms are sold in the shop; evolved forms are
-- evolution-only (price 0). INSERT OR IGNORE leaves existing rows untouched, and each
-- character has at most one outgoing evolution path.

INSERT OR IGNORE INTO characters (id, external_id, name, slug, type_primary, type_secondary, image_url, price, rarity) VALUES
  ('char_torchic', '255', 'Torchic', 'torchic', 'Fire', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/255.png', 400, 'COMMON'),
  ('char_combusken', '256', 'Combusken', 'combusken', 'Fire', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/256.png', 0, 'RARE'),
  ('char_blaziken', '257', 'Blaziken', 'blaziken', 'Fire', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/257.png', 0, 'EPIC'),
  ('char_mudkip', '258', 'Mudkip', 'mudkip', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/258.png', 400, 'COMMON'),
  ('char_marshtomp', '259', 'Marshtomp', 'marshtomp', 'Water', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/259.png', 0, 'RARE'),
  ('char_swampert', '260', 'Swampert', 'swampert', 'Water', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/260.png', 0, 'EPIC'),
  ('char_turtwig', '387', 'Turtwig', 'turtwig', 'Grass', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/387.png', 400, 'COMMON'),
  ('char_grotle', '388', 'Grotle', 'grotle', 'Grass', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/388.png', 0, 'RARE'),
  ('char_torterra', '389', 'Torterra', 'torterra', 'Grass', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/389.png', 0, 'EPIC'),
  ('char_chimchar', '390', 'Chimchar', 'chimchar', 'Fire', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/390.png', 400, 'COMMON'),
  ('char_monferno', '391', 'Monferno', 'monferno', 'Fire', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/391.png', 0, 'RARE'),
  ('char_infernape', '392', 'Infernape', 'infernape', 'Fire', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/392.png', 0, 'EPIC'),
  ('char_piplup', '393', 'Piplup', 'piplup', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/393.png', 400, 'COMMON'),
  ('char_prinplup', '394', 'Prinplup', 'prinplup', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/394.png', 0, 'RARE'),
  ('char_empoleon', '395', 'Empoleon', 'empoleon', 'Water', 'Steel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/395.png', 0, 'EPIC'),
  ('char_froakie', '656', 'Froakie', 'froakie', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/656.png', 450, 'COMMON'),
  ('char_frogadier', '657', 'Frogadier', 'frogadier', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/657.png', 0, 'RARE'),
  ('char_greninja', '658', 'Greninja', 'greninja', 'Water', 'Dark', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/658.png', 0, 'EPIC'),
  ('char_rowlet', '722', 'Rowlet', 'rowlet', 'Grass', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/722.png', 450, 'COMMON'),
  ('char_dartrix', '723', 'Dartrix', 'dartrix', 'Grass', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/723.png', 0, 'RARE'),
  ('char_decidueye', '724', 'Decidueye', 'decidueye', 'Grass', 'Ghost', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/724.png', 0, 'EPIC'),
  ('char_shinx', '403', 'Shinx', 'shinx', 'Electric', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/403.png', 350, 'COMMON'),
  ('char_luxio', '404', 'Luxio', 'luxio', 'Electric', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/404.png', 0, 'RARE'),
  ('char_luxray', '405', 'Luxray', 'luxray', 'Electric', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/405.png', 0, 'EPIC'),
  ('char_mareep', '179', 'Mareep', 'mareep', 'Electric', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/179.png', 350, 'COMMON'),
  ('char_flaaffy', '180', 'Flaaffy', 'flaaffy', 'Electric', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/180.png', 0, 'RARE'),
  ('char_ampharos', '181', 'Ampharos', 'ampharos', 'Electric', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/181.png', 0, 'EPIC'),
  ('char_ralts', '280', 'Ralts', 'ralts', 'Psychic', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/280.png', 450, 'COMMON'),
  ('char_kirlia', '281', 'Kirlia', 'kirlia', 'Psychic', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/281.png', 0, 'RARE'),
  ('char_gardevoir', '282', 'Gardevoir', 'gardevoir', 'Psychic', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/282.png', 0, 'EPIC'),
  ('char_aron', '304', 'Aron', 'aron', 'Steel', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/304.png', 400, 'COMMON'),
  ('char_lairon', '305', 'Lairon', 'lairon', 'Steel', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/305.png', 0, 'RARE'),
  ('char_aggron', '306', 'Aggron', 'aggron', 'Steel', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/306.png', 0, 'EPIC'),
  ('char_litwick', '607', 'Litwick', 'litwick', 'Ghost', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/607.png', 450, 'COMMON'),
  ('char_lampent', '608', 'Lampent', 'lampent', 'Ghost', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/608.png', 0, 'RARE'),
  ('char_chandelure', '609', 'Chandelure', 'chandelure', 'Ghost', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/609.png', 0, 'EPIC'),
  ('char_larvitar', '246', 'Larvitar', 'larvitar', 'Rock', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/246.png', 600, 'RARE'),
  ('char_pupitar', '247', 'Pupitar', 'pupitar', 'Rock', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/247.png', 0, 'EPIC'),
  ('char_tyranitar', '248', 'Tyranitar', 'tyranitar', 'Rock', 'Dark', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/248.png', 0, 'LEGENDARY'),
  ('char_bagon', '371', 'Bagon', 'bagon', 'Dragon', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/371.png', 600, 'RARE'),
  ('char_shelgon', '372', 'Shelgon', 'shelgon', 'Dragon', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/372.png', 0, 'EPIC'),
  ('char_salamence', '373', 'Salamence', 'salamence', 'Dragon', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/373.png', 0, 'LEGENDARY'),
  ('char_beldum', '374', 'Beldum', 'beldum', 'Steel', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/374.png', 600, 'RARE'),
  ('char_metang', '375', 'Metang', 'metang', 'Steel', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/375.png', 0, 'EPIC'),
  ('char_metagross', '376', 'Metagross', 'metagross', 'Steel', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/376.png', 0, 'LEGENDARY'),
  ('char_gible', '443', 'Gible', 'gible', 'Dragon', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/443.png', 600, 'RARE'),
  ('char_gabite', '444', 'Gabite', 'gabite', 'Dragon', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/444.png', 0, 'EPIC'),
  ('char_garchomp', '445', 'Garchomp', 'garchomp', 'Dragon', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/445.png', 0, 'LEGENDARY'),
  ('char_axew', '610', 'Axew', 'axew', 'Dragon', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/610.png', 600, 'RARE'),
  ('char_fraxure', '611', 'Fraxure', 'fraxure', 'Dragon', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/611.png', 0, 'EPIC'),
  ('char_haxorus', '612', 'Haxorus', 'haxorus', 'Dragon', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/612.png', 0, 'LEGENDARY'),
  ('char_snorunt', '361', 'Snorunt', 'snorunt', 'Ice', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/361.png', 350, 'COMMON'),
  ('char_glalie', '362', 'Glalie', 'glalie', 'Ice', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/362.png', 0, 'RARE'),
  ('char_zorua', '570', 'Zorua', 'zorua', 'Dark', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/570.png', 500, 'RARE'),
  ('char_zoroark', '571', 'Zoroark', 'zoroark', 'Dark', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/571.png', 0, 'EPIC'),
  ('char_rayquaza', '384', 'Rayquaza', 'rayquaza', 'Dragon', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/384.png', 3000, 'LEGENDARY'),
  ('char_lugia', '249', 'Lugia', 'lugia', 'Psychic', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/249.png', 2500, 'LEGENDARY'),
  ('char_hooh', '250', 'Ho-Oh', 'ho-oh', 'Fire', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/250.png', 2500, 'LEGENDARY'),
  ('char_kyogre', '382', 'Kyogre', 'kyogre', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/382.png', 2500, 'LEGENDARY'),
  ('char_groudon', '383', 'Groudon', 'groudon', 'Ground', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/383.png', 2500, 'LEGENDARY');

INSERT OR IGNORE INTO evolution_paths (id, from_character_id, to_character_id, point_cost) VALUES
  ('evo_torchic_combusken', 'char_torchic', 'char_combusken', 600),
  ('evo_combusken_blaziken', 'char_combusken', 'char_blaziken', 1000),
  ('evo_mudkip_marshtomp', 'char_mudkip', 'char_marshtomp', 600),
  ('evo_marshtomp_swampert', 'char_marshtomp', 'char_swampert', 1000),
  ('evo_turtwig_grotle', 'char_turtwig', 'char_grotle', 600),
  ('evo_grotle_torterra', 'char_grotle', 'char_torterra', 1000),
  ('evo_chimchar_monferno', 'char_chimchar', 'char_monferno', 600),
  ('evo_monferno_infernape', 'char_monferno', 'char_infernape', 1000),
  ('evo_piplup_prinplup', 'char_piplup', 'char_prinplup', 600),
  ('evo_prinplup_empoleon', 'char_prinplup', 'char_empoleon', 1000),
  ('evo_froakie_frogadier', 'char_froakie', 'char_frogadier', 600),
  ('evo_frogadier_greninja', 'char_frogadier', 'char_greninja', 1000),
  ('evo_rowlet_dartrix', 'char_rowlet', 'char_dartrix', 600),
  ('evo_dartrix_decidueye', 'char_dartrix', 'char_decidueye', 1000),
  ('evo_shinx_luxio', 'char_shinx', 'char_luxio', 600),
  ('evo_luxio_luxray', 'char_luxio', 'char_luxray', 1000),
  ('evo_mareep_flaaffy', 'char_mareep', 'char_flaaffy', 600),
  ('evo_flaaffy_ampharos', 'char_flaaffy', 'char_ampharos', 1000),
  ('evo_ralts_kirlia', 'char_ralts', 'char_kirlia', 600),
  ('evo_kirlia_gardevoir', 'char_kirlia', 'char_gardevoir', 1000),
  ('evo_aron_lairon', 'char_aron', 'char_lairon', 600),
  ('evo_lairon_aggron', 'char_lairon', 'char_aggron', 1000),
  ('evo_litwick_lampent', 'char_litwick', 'char_lampent', 600),
  ('evo_lampent_chandelure', 'char_lampent', 'char_chandelure', 1000),
  ('evo_larvitar_pupitar', 'char_larvitar', 'char_pupitar', 1000),
  ('evo_pupitar_tyranitar', 'char_pupitar', 'char_tyranitar', 1500),
  ('evo_bagon_shelgon', 'char_bagon', 'char_shelgon', 1000),
  ('evo_shelgon_salamence', 'char_shelgon', 'char_salamence', 1500),
  ('evo_beldum_metang', 'char_beldum', 'char_metang', 1000),
  ('evo_metang_metagross', 'char_metang', 'char_metagross', 1500),
  ('evo_gible_gabite', 'char_gible', 'char_gabite', 1000),
  ('evo_gabite_garchomp', 'char_gabite', 'char_garchomp', 1500),
  ('evo_axew_fraxure', 'char_axew', 'char_fraxure', 1000),
  ('evo_fraxure_haxorus', 'char_fraxure', 'char_haxorus', 1500),
  ('evo_snorunt_glalie', 'char_snorunt', 'char_glalie', 800),
  ('evo_zorua_zoroark', 'char_zorua', 'char_zoroark', 1000);
