-- Adds 30 more characters as ten three-stage lines: eight starters (Johto, Alola,
-- Galar) and two pseudo-legendary dragons (Kommo-o, Dragapult). Base forms are sold
-- in the shop; evolved forms are evolution-only (price 0). INSERT OR IGNORE leaves
-- existing rows untouched, and each character has at most one outgoing evolution path.

INSERT OR IGNORE INTO characters (id, external_id, name, slug, type_primary, type_secondary, image_url, price, rarity) VALUES
  ('char_chikorita', '152', 'Chikorita', 'chikorita', 'Grass', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/152.png', 400, 'COMMON'),
  ('char_bayleef', '153', 'Bayleef', 'bayleef', 'Grass', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/153.png', 0, 'RARE'),
  ('char_meganium', '154', 'Meganium', 'meganium', 'Grass', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/154.png', 0, 'EPIC'),
  ('char_cyndaquil', '155', 'Cyndaquil', 'cyndaquil', 'Fire', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/155.png', 400, 'COMMON'),
  ('char_quilava', '156', 'Quilava', 'quilava', 'Fire', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/156.png', 0, 'RARE'),
  ('char_typhlosion', '157', 'Typhlosion', 'typhlosion', 'Fire', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/157.png', 0, 'EPIC'),
  ('char_totodile', '158', 'Totodile', 'totodile', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/158.png', 400, 'COMMON'),
  ('char_croconaw', '159', 'Croconaw', 'croconaw', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/159.png', 0, 'RARE'),
  ('char_feraligatr', '160', 'Feraligatr', 'feraligatr', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/160.png', 0, 'EPIC'),
  ('char_litten', '725', 'Litten', 'litten', 'Fire', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/725.png', 450, 'COMMON'),
  ('char_torracat', '726', 'Torracat', 'torracat', 'Fire', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/726.png', 0, 'RARE'),
  ('char_incineroar', '727', 'Incineroar', 'incineroar', 'Fire', 'Dark', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/727.png', 0, 'EPIC'),
  ('char_popplio', '728', 'Popplio', 'popplio', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/728.png', 450, 'COMMON'),
  ('char_brionne', '729', 'Brionne', 'brionne', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/729.png', 0, 'RARE'),
  ('char_primarina', '730', 'Primarina', 'primarina', 'Water', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/730.png', 0, 'EPIC'),
  ('char_grookey', '810', 'Grookey', 'grookey', 'Grass', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/810.png', 450, 'COMMON'),
  ('char_thwackey', '811', 'Thwackey', 'thwackey', 'Grass', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/811.png', 0, 'RARE'),
  ('char_rillaboom', '812', 'Rillaboom', 'rillaboom', 'Grass', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/812.png', 0, 'EPIC'),
  ('char_scorbunny', '813', 'Scorbunny', 'scorbunny', 'Fire', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/813.png', 450, 'COMMON'),
  ('char_raboot', '814', 'Raboot', 'raboot', 'Fire', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/814.png', 0, 'RARE'),
  ('char_cinderace', '815', 'Cinderace', 'cinderace', 'Fire', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/815.png', 0, 'EPIC'),
  ('char_sobble', '816', 'Sobble', 'sobble', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/816.png', 450, 'COMMON'),
  ('char_drizzile', '817', 'Drizzile', 'drizzile', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/817.png', 0, 'RARE'),
  ('char_inteleon', '818', 'Inteleon', 'inteleon', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/818.png', 0, 'EPIC'),
  ('char_jangmoo', '782', 'Jangmo-o', 'jangmo-o', 'Dragon', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/782.png', 600, 'RARE'),
  ('char_hakamoo', '783', 'Hakamo-o', 'hakamo-o', 'Dragon', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/783.png', 0, 'EPIC'),
  ('char_kommoo', '784', 'Kommo-o', 'kommo-o', 'Dragon', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/784.png', 0, 'LEGENDARY'),
  ('char_dreepy', '885', 'Dreepy', 'dreepy', 'Dragon', 'Ghost', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/885.png', 600, 'RARE'),
  ('char_drakloak', '886', 'Drakloak', 'drakloak', 'Dragon', 'Ghost', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/886.png', 0, 'EPIC'),
  ('char_dragapult', '887', 'Dragapult', 'dragapult', 'Dragon', 'Ghost', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/887.png', 0, 'LEGENDARY');

INSERT OR IGNORE INTO evolution_paths (id, from_character_id, to_character_id, point_cost) VALUES
  ('evo_chikorita_bayleef', 'char_chikorita', 'char_bayleef', 600),
  ('evo_bayleef_meganium', 'char_bayleef', 'char_meganium', 1000),
  ('evo_cyndaquil_quilava', 'char_cyndaquil', 'char_quilava', 600),
  ('evo_quilava_typhlosion', 'char_quilava', 'char_typhlosion', 1000),
  ('evo_totodile_croconaw', 'char_totodile', 'char_croconaw', 600),
  ('evo_croconaw_feraligatr', 'char_croconaw', 'char_feraligatr', 1000),
  ('evo_litten_torracat', 'char_litten', 'char_torracat', 600),
  ('evo_torracat_incineroar', 'char_torracat', 'char_incineroar', 1000),
  ('evo_popplio_brionne', 'char_popplio', 'char_brionne', 600),
  ('evo_brionne_primarina', 'char_brionne', 'char_primarina', 1000),
  ('evo_grookey_thwackey', 'char_grookey', 'char_thwackey', 600),
  ('evo_thwackey_rillaboom', 'char_thwackey', 'char_rillaboom', 1000),
  ('evo_scorbunny_raboot', 'char_scorbunny', 'char_raboot', 600),
  ('evo_raboot_cinderace', 'char_raboot', 'char_cinderace', 1000),
  ('evo_sobble_drizzile', 'char_sobble', 'char_drizzile', 600),
  ('evo_drizzile_inteleon', 'char_drizzile', 'char_inteleon', 1000),
  ('evo_jangmoo_hakamoo', 'char_jangmoo', 'char_hakamoo', 1000),
  ('evo_hakamoo_kommoo', 'char_hakamoo', 'char_kommoo', 1500),
  ('evo_dreepy_drakloak', 'char_dreepy', 'char_drakloak', 1000),
  ('evo_drakloak_dragapult', 'char_drakloak', 'char_dragapult', 1500);
