-- The big batch: 137 more characters.
-- * 16 new three-stage lines (Weedle, both Nidoran, Zubat, Bellsprout, Rhyhorn, Porygon,
--   Duskull, Slakoth, Tynamo, Timburr, Sandile, Rookidee, Rolycoly, Nacli, Tinkatink).
-- * 32 new two-stage lines, including Feebas -> Milotic and Meltan -> Melmetal.
-- * Final forms for four lines already in the game: Seadra -> Kingdra,
--   Magneton -> Magnezone, Piloswine -> Mamoswine, Togetic -> Togekiss.
-- * 21 more shop legendaries (the Regis, Swords of Justice, Forces of Nature, Kyurem,
--   Heatran, Cresselia, and mythicals Victini to Zeraora).
-- Names and types were checked against PokeAPI. Base forms are sold in the shop and
-- evolved forms are evolution-only (price 0). INSERT OR IGNORE leaves existing rows
-- untouched, and each character has at most one outgoing evolution path.

INSERT OR IGNORE INTO characters (id, external_id, name, slug, type_primary, type_secondary, image_url, price, rarity) VALUES
  ('char_weedle', '13', 'Weedle', 'weedle', 'Bug', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/13.png', 300, 'COMMON'),
  ('char_kakuna', '14', 'Kakuna', 'kakuna', 'Bug', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/14.png', 0, 'RARE'),
  ('char_beedrill', '15', 'Beedrill', 'beedrill', 'Bug', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/15.png', 0, 'EPIC'),
  ('char_nidoranf', '29', 'Nidoran♀', 'nidoran-f', 'Poison', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/29.png', 350, 'COMMON'),
  ('char_nidorina', '30', 'Nidorina', 'nidorina', 'Poison', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/30.png', 0, 'RARE'),
  ('char_nidoqueen', '31', 'Nidoqueen', 'nidoqueen', 'Poison', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/31.png', 0, 'EPIC'),
  ('char_nidoranm', '32', 'Nidoran♂', 'nidoran-m', 'Poison', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/32.png', 350, 'COMMON'),
  ('char_nidorino', '33', 'Nidorino', 'nidorino', 'Poison', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/33.png', 0, 'RARE'),
  ('char_nidoking', '34', 'Nidoking', 'nidoking', 'Poison', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/34.png', 0, 'EPIC'),
  ('char_zubat', '41', 'Zubat', 'zubat', 'Poison', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/41.png', 300, 'COMMON'),
  ('char_golbat', '42', 'Golbat', 'golbat', 'Poison', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/42.png', 0, 'RARE'),
  ('char_crobat', '169', 'Crobat', 'crobat', 'Poison', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/169.png', 0, 'EPIC'),
  ('char_bellsprout', '69', 'Bellsprout', 'bellsprout', 'Grass', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/69.png', 300, 'COMMON'),
  ('char_weepinbell', '70', 'Weepinbell', 'weepinbell', 'Grass', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/70.png', 0, 'RARE'),
  ('char_victreebel', '71', 'Victreebel', 'victreebel', 'Grass', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/71.png', 0, 'EPIC'),
  ('char_rhyhorn', '111', 'Rhyhorn', 'rhyhorn', 'Ground', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/111.png', 450, 'COMMON'),
  ('char_rhydon', '112', 'Rhydon', 'rhydon', 'Ground', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/112.png', 0, 'RARE'),
  ('char_rhyperior', '464', 'Rhyperior', 'rhyperior', 'Ground', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/464.png', 0, 'EPIC'),
  ('char_porygon', '137', 'Porygon', 'porygon', 'Normal', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/137.png', 450, 'COMMON'),
  ('char_porygon2', '233', 'Porygon2', 'porygon2', 'Normal', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/233.png', 0, 'RARE'),
  ('char_porygonz', '474', 'Porygon-Z', 'porygon-z', 'Normal', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/474.png', 0, 'EPIC'),
  ('char_duskull', '355', 'Duskull', 'duskull', 'Ghost', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/355.png', 400, 'COMMON'),
  ('char_dusclops', '356', 'Dusclops', 'dusclops', 'Ghost', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/356.png', 0, 'RARE'),
  ('char_dusknoir', '477', 'Dusknoir', 'dusknoir', 'Ghost', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/477.png', 0, 'EPIC'),
  ('char_slakoth', '287', 'Slakoth', 'slakoth', 'Normal', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/287.png', 400, 'COMMON'),
  ('char_vigoroth', '288', 'Vigoroth', 'vigoroth', 'Normal', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/288.png', 0, 'RARE'),
  ('char_slaking', '289', 'Slaking', 'slaking', 'Normal', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/289.png', 0, 'EPIC'),
  ('char_tynamo', '602', 'Tynamo', 'tynamo', 'Electric', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/602.png', 400, 'COMMON'),
  ('char_eelektrik', '603', 'Eelektrik', 'eelektrik', 'Electric', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/603.png', 0, 'RARE'),
  ('char_eelektross', '604', 'Eelektross', 'eelektross', 'Electric', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/604.png', 0, 'EPIC'),
  ('char_timburr', '532', 'Timburr', 'timburr', 'Fighting', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/532.png', 400, 'COMMON'),
  ('char_gurdurr', '533', 'Gurdurr', 'gurdurr', 'Fighting', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/533.png', 0, 'RARE'),
  ('char_conkeldurr', '534', 'Conkeldurr', 'conkeldurr', 'Fighting', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/534.png', 0, 'EPIC'),
  ('char_sandile', '551', 'Sandile', 'sandile', 'Ground', 'Dark', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/551.png', 400, 'COMMON'),
  ('char_krokorok', '552', 'Krokorok', 'krokorok', 'Ground', 'Dark', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/552.png', 0, 'RARE'),
  ('char_krookodile', '553', 'Krookodile', 'krookodile', 'Ground', 'Dark', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/553.png', 0, 'EPIC'),
  ('char_rookidee', '821', 'Rookidee', 'rookidee', 'Flying', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/821.png', 400, 'COMMON'),
  ('char_corvisquire', '822', 'Corvisquire', 'corvisquire', 'Flying', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/822.png', 0, 'RARE'),
  ('char_corviknight', '823', 'Corviknight', 'corviknight', 'Flying', 'Steel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/823.png', 0, 'EPIC'),
  ('char_rolycoly', '837', 'Rolycoly', 'rolycoly', 'Rock', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/837.png', 400, 'COMMON'),
  ('char_carkol', '838', 'Carkol', 'carkol', 'Rock', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/838.png', 0, 'RARE'),
  ('char_coalossal', '839', 'Coalossal', 'coalossal', 'Rock', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/839.png', 0, 'EPIC'),
  ('char_nacli', '932', 'Nacli', 'nacli', 'Rock', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/932.png', 400, 'COMMON'),
  ('char_naclstack', '933', 'Naclstack', 'naclstack', 'Rock', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/933.png', 0, 'RARE'),
  ('char_garganacl', '934', 'Garganacl', 'garganacl', 'Rock', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/934.png', 0, 'EPIC'),
  ('char_tinkatink', '957', 'Tinkatink', 'tinkatink', 'Fairy', 'Steel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/957.png', 450, 'COMMON'),
  ('char_tinkatuff', '958', 'Tinkatuff', 'tinkatuff', 'Fairy', 'Steel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/958.png', 0, 'RARE'),
  ('char_tinkaton', '959', 'Tinkaton', 'tinkaton', 'Fairy', 'Steel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/959.png', 0, 'EPIC'),
  ('char_tentacool', '72', 'Tentacool', 'tentacool', 'Water', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/72.png', 350, 'COMMON'),
  ('char_tentacruel', '73', 'Tentacruel', 'tentacruel', 'Water', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/73.png', 0, 'RARE'),
  ('char_doduo', '84', 'Doduo', 'doduo', 'Normal', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/84.png', 350, 'COMMON'),
  ('char_dodrio', '85', 'Dodrio', 'dodrio', 'Normal', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/85.png', 0, 'RARE'),
  ('char_grimer', '88', 'Grimer', 'grimer', 'Poison', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/88.png', 350, 'COMMON'),
  ('char_muk', '89', 'Muk', 'muk', 'Poison', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/89.png', 0, 'RARE'),
  ('char_shellder', '90', 'Shellder', 'shellder', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/90.png', 350, 'COMMON'),
  ('char_cloyster', '91', 'Cloyster', 'cloyster', 'Water', 'Ice', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/91.png', 0, 'RARE'),
  ('char_drowzee', '96', 'Drowzee', 'drowzee', 'Psychic', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/96.png', 350, 'COMMON'),
  ('char_hypno', '97', 'Hypno', 'hypno', 'Psychic', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/97.png', 0, 'RARE'),
  ('char_krabby', '98', 'Krabby', 'krabby', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/98.png', 350, 'COMMON'),
  ('char_kingler', '99', 'Kingler', 'kingler', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/99.png', 0, 'RARE'),
  ('char_voltorb', '100', 'Voltorb', 'voltorb', 'Electric', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/100.png', 350, 'COMMON'),
  ('char_electrode', '101', 'Electrode', 'electrode', 'Electric', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/101.png', 0, 'RARE'),
  ('char_exeggcute', '102', 'Exeggcute', 'exeggcute', 'Grass', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/102.png', 400, 'COMMON'),
  ('char_exeggutor', '103', 'Exeggutor', 'exeggutor', 'Grass', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/103.png', 0, 'RARE'),
  ('char_koffing', '109', 'Koffing', 'koffing', 'Poison', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/109.png', 350, 'COMMON'),
  ('char_weezing', '110', 'Weezing', 'weezing', 'Poison', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/110.png', 0, 'RARE'),
  ('char_tangela', '114', 'Tangela', 'tangela', 'Grass', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/114.png', 400, 'COMMON'),
  ('char_tangrowth', '465', 'Tangrowth', 'tangrowth', 'Grass', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/465.png', 0, 'RARE'),
  ('char_makuhita', '296', 'Makuhita', 'makuhita', 'Fighting', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/296.png', 350, 'COMMON'),
  ('char_hariyama', '297', 'Hariyama', 'hariyama', 'Fighting', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/297.png', 0, 'RARE'),
  ('char_carvanha', '318', 'Carvanha', 'carvanha', 'Water', 'Dark', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/318.png', 350, 'COMMON'),
  ('char_sharpedo', '319', 'Sharpedo', 'sharpedo', 'Water', 'Dark', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/319.png', 0, 'RARE'),
  ('char_wailmer', '320', 'Wailmer', 'wailmer', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/320.png', 400, 'COMMON'),
  ('char_wailord', '321', 'Wailord', 'wailord', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/321.png', 0, 'RARE'),
  ('char_numel', '322', 'Numel', 'numel', 'Fire', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/322.png', 350, 'COMMON'),
  ('char_camerupt', '323', 'Camerupt', 'camerupt', 'Fire', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/323.png', 0, 'RARE'),
  ('char_feebas', '349', 'Feebas', 'feebas', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/349.png', 300, 'COMMON'),
  ('char_milotic', '350', 'Milotic', 'milotic', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/350.png', 0, 'EPIC'),
  ('char_shuppet', '353', 'Shuppet', 'shuppet', 'Ghost', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/353.png', 350, 'COMMON'),
  ('char_banette', '354', 'Banette', 'banette', 'Ghost', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/354.png', 0, 'RARE'),
  ('char_buizel', '418', 'Buizel', 'buizel', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/418.png', 350, 'COMMON'),
  ('char_floatzel', '419', 'Floatzel', 'floatzel', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/419.png', 0, 'RARE'),
  ('char_croagunk', '453', 'Croagunk', 'croagunk', 'Poison', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/453.png', 350, 'COMMON'),
  ('char_toxicroak', '454', 'Toxicroak', 'toxicroak', 'Poison', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/454.png', 0, 'RARE'),
  ('char_gligar', '207', 'Gligar', 'gligar', 'Ground', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/207.png', 400, 'COMMON'),
  ('char_gliscor', '472', 'Gliscor', 'gliscor', 'Ground', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/472.png', 0, 'RARE'),
  ('char_murkrow', '198', 'Murkrow', 'murkrow', 'Dark', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/198.png', 400, 'COMMON'),
  ('char_honchkrow', '430', 'Honchkrow', 'honchkrow', 'Dark', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/430.png', 0, 'RARE'),
  ('char_misdreavus', '200', 'Misdreavus', 'misdreavus', 'Ghost', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/200.png', 400, 'COMMON'),
  ('char_mismagius', '429', 'Mismagius', 'mismagius', 'Ghost', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/429.png', 0, 'RARE'),
  ('char_yanma', '193', 'Yanma', 'yanma', 'Bug', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/193.png', 400, 'COMMON'),
  ('char_yanmega', '469', 'Yanmega', 'yanmega', 'Bug', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/469.png', 0, 'RARE'),
  ('char_joltik', '595', 'Joltik', 'joltik', 'Bug', 'Electric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/595.png', 350, 'COMMON'),
  ('char_galvantula', '596', 'Galvantula', 'galvantula', 'Bug', 'Electric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/596.png', 0, 'RARE'),
  ('char_ferroseed', '597', 'Ferroseed', 'ferroseed', 'Grass', 'Steel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/597.png', 400, 'COMMON'),
  ('char_ferrothorn', '598', 'Ferrothorn', 'ferrothorn', 'Grass', 'Steel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/598.png', 0, 'RARE'),
  ('char_litleo', '667', 'Litleo', 'litleo', 'Fire', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/667.png', 400, 'COMMON'),
  ('char_pyroar', '668', 'Pyroar', 'pyroar', 'Fire', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/668.png', 0, 'RARE'),
  ('char_noibat', '714', 'Noibat', 'noibat', 'Flying', 'Dragon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/714.png', 600, 'RARE'),
  ('char_noivern', '715', 'Noivern', 'noivern', 'Flying', 'Dragon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/715.png', 0, 'EPIC'),
  ('char_mudbray', '749', 'Mudbray', 'mudbray', 'Ground', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/749.png', 400, 'COMMON'),
  ('char_mudsdale', '750', 'Mudsdale', 'mudsdale', 'Ground', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/750.png', 0, 'RARE'),
  ('char_toxel', '848', 'Toxel', 'toxel', 'Electric', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/848.png', 450, 'COMMON'),
  ('char_toxtricity', '849', 'Toxtricity', 'toxtricity', 'Electric', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/849.png', 0, 'RARE'),
  ('char_cufant', '878', 'Cufant', 'cufant', 'Steel', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/878.png', 400, 'COMMON'),
  ('char_copperajah', '879', 'Copperajah', 'copperajah', 'Steel', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/879.png', 0, 'RARE'),
  ('char_charcadet', '935', 'Charcadet', 'charcadet', 'Fire', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/935.png', 600, 'RARE'),
  ('char_armarouge', '936', 'Armarouge', 'armarouge', 'Fire', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/936.png', 0, 'EPIC'),
  ('char_fidough', '926', 'Fidough', 'fidough', 'Fairy', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/926.png', 350, 'COMMON'),
  ('char_dachsbun', '927', 'Dachsbun', 'dachsbun', 'Fairy', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/927.png', 0, 'RARE'),
  ('char_meltan', '808', 'Meltan', 'meltan', 'Steel', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/808.png', 1500, 'EPIC'),
  ('char_melmetal', '809', 'Melmetal', 'melmetal', 'Steel', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/809.png', 0, 'LEGENDARY'),
  ('char_kingdra', '230', 'Kingdra', 'kingdra', 'Water', 'Dragon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/230.png', 0, 'EPIC'),
  ('char_magnezone', '462', 'Magnezone', 'magnezone', 'Electric', 'Steel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/462.png', 0, 'EPIC'),
  ('char_mamoswine', '473', 'Mamoswine', 'mamoswine', 'Ice', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/473.png', 0, 'EPIC'),
  ('char_togekiss', '468', 'Togekiss', 'togekiss', 'Fairy', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/468.png', 0, 'EPIC'),
  ('char_regirock', '377', 'Regirock', 'regirock', 'Rock', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/377.png', 2000, 'LEGENDARY'),
  ('char_regice', '378', 'Regice', 'regice', 'Ice', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/378.png', 2000, 'LEGENDARY'),
  ('char_registeel', '379', 'Registeel', 'registeel', 'Steel', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/379.png', 2000, 'LEGENDARY'),
  ('char_regigigas', '486', 'Regigigas', 'regigigas', 'Normal', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/486.png', 2500, 'LEGENDARY'),
  ('char_cobalion', '638', 'Cobalion', 'cobalion', 'Steel', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/638.png', 2000, 'LEGENDARY'),
  ('char_terrakion', '639', 'Terrakion', 'terrakion', 'Rock', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/639.png', 2000, 'LEGENDARY'),
  ('char_virizion', '640', 'Virizion', 'virizion', 'Grass', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/640.png', 2000, 'LEGENDARY'),
  ('char_tornadus', '641', 'Tornadus', 'tornadus', 'Flying', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/641.png', 2000, 'LEGENDARY'),
  ('char_thundurus', '642', 'Thundurus', 'thundurus', 'Electric', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/642.png', 2000, 'LEGENDARY'),
  ('char_landorus', '645', 'Landorus', 'landorus', 'Ground', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/645.png', 2000, 'LEGENDARY'),
  ('char_kyurem', '646', 'Kyurem', 'kyurem', 'Dragon', 'Ice', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/646.png', 2500, 'LEGENDARY'),
  ('char_heatran', '485', 'Heatran', 'heatran', 'Fire', 'Steel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/485.png', 2500, 'LEGENDARY'),
  ('char_cresselia', '488', 'Cresselia', 'cresselia', 'Psychic', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/488.png', 2500, 'LEGENDARY'),
  ('char_victini', '494', 'Victini', 'victini', 'Psychic', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/494.png', 3000, 'LEGENDARY'),
  ('char_genesect', '649', 'Genesect', 'genesect', 'Bug', 'Steel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/649.png', 3000, 'LEGENDARY'),
  ('char_diancie', '719', 'Diancie', 'diancie', 'Rock', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/719.png', 3000, 'LEGENDARY'),
  ('char_hoopa', '720', 'Hoopa', 'hoopa', 'Psychic', 'Ghost', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/720.png', 3000, 'LEGENDARY'),
  ('char_volcanion', '721', 'Volcanion', 'volcanion', 'Fire', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/721.png', 3000, 'LEGENDARY'),
  ('char_magearna', '801', 'Magearna', 'magearna', 'Steel', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/801.png', 3000, 'LEGENDARY'),
  ('char_marshadow', '802', 'Marshadow', 'marshadow', 'Fighting', 'Ghost', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/802.png', 3000, 'LEGENDARY'),
  ('char_zeraora', '807', 'Zeraora', 'zeraora', 'Electric', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/807.png', 3000, 'LEGENDARY');

INSERT OR IGNORE INTO evolution_paths (id, from_character_id, to_character_id, point_cost) VALUES
  ('evo_weedle_kakuna', 'char_weedle', 'char_kakuna', 600),
  ('evo_kakuna_beedrill', 'char_kakuna', 'char_beedrill', 1000),
  ('evo_nidoranf_nidorina', 'char_nidoranf', 'char_nidorina', 600),
  ('evo_nidorina_nidoqueen', 'char_nidorina', 'char_nidoqueen', 1000),
  ('evo_nidoranm_nidorino', 'char_nidoranm', 'char_nidorino', 600),
  ('evo_nidorino_nidoking', 'char_nidorino', 'char_nidoking', 1000),
  ('evo_zubat_golbat', 'char_zubat', 'char_golbat', 600),
  ('evo_golbat_crobat', 'char_golbat', 'char_crobat', 1000),
  ('evo_bellsprout_weepinbell', 'char_bellsprout', 'char_weepinbell', 600),
  ('evo_weepinbell_victreebel', 'char_weepinbell', 'char_victreebel', 1000),
  ('evo_rhyhorn_rhydon', 'char_rhyhorn', 'char_rhydon', 600),
  ('evo_rhydon_rhyperior', 'char_rhydon', 'char_rhyperior', 1000),
  ('evo_porygon_porygon2', 'char_porygon', 'char_porygon2', 600),
  ('evo_porygon2_porygonz', 'char_porygon2', 'char_porygonz', 1000),
  ('evo_duskull_dusclops', 'char_duskull', 'char_dusclops', 600),
  ('evo_dusclops_dusknoir', 'char_dusclops', 'char_dusknoir', 1000),
  ('evo_slakoth_vigoroth', 'char_slakoth', 'char_vigoroth', 600),
  ('evo_vigoroth_slaking', 'char_vigoroth', 'char_slaking', 1000),
  ('evo_tynamo_eelektrik', 'char_tynamo', 'char_eelektrik', 600),
  ('evo_eelektrik_eelektross', 'char_eelektrik', 'char_eelektross', 1000),
  ('evo_timburr_gurdurr', 'char_timburr', 'char_gurdurr', 600),
  ('evo_gurdurr_conkeldurr', 'char_gurdurr', 'char_conkeldurr', 1000),
  ('evo_sandile_krokorok', 'char_sandile', 'char_krokorok', 600),
  ('evo_krokorok_krookodile', 'char_krokorok', 'char_krookodile', 1000),
  ('evo_rookidee_corvisquire', 'char_rookidee', 'char_corvisquire', 600),
  ('evo_corvisquire_corviknight', 'char_corvisquire', 'char_corviknight', 1000),
  ('evo_rolycoly_carkol', 'char_rolycoly', 'char_carkol', 600),
  ('evo_carkol_coalossal', 'char_carkol', 'char_coalossal', 1000),
  ('evo_nacli_naclstack', 'char_nacli', 'char_naclstack', 600),
  ('evo_naclstack_garganacl', 'char_naclstack', 'char_garganacl', 1000),
  ('evo_tinkatink_tinkatuff', 'char_tinkatink', 'char_tinkatuff', 600),
  ('evo_tinkatuff_tinkaton', 'char_tinkatuff', 'char_tinkaton', 1000),
  ('evo_tentacool_tentacruel', 'char_tentacool', 'char_tentacruel', 800),
  ('evo_doduo_dodrio', 'char_doduo', 'char_dodrio', 800),
  ('evo_grimer_muk', 'char_grimer', 'char_muk', 800),
  ('evo_shellder_cloyster', 'char_shellder', 'char_cloyster', 800),
  ('evo_drowzee_hypno', 'char_drowzee', 'char_hypno', 800),
  ('evo_krabby_kingler', 'char_krabby', 'char_kingler', 800),
  ('evo_voltorb_electrode', 'char_voltorb', 'char_electrode', 800),
  ('evo_exeggcute_exeggutor', 'char_exeggcute', 'char_exeggutor', 800),
  ('evo_koffing_weezing', 'char_koffing', 'char_weezing', 800),
  ('evo_tangela_tangrowth', 'char_tangela', 'char_tangrowth', 800),
  ('evo_makuhita_hariyama', 'char_makuhita', 'char_hariyama', 800),
  ('evo_carvanha_sharpedo', 'char_carvanha', 'char_sharpedo', 800),
  ('evo_wailmer_wailord', 'char_wailmer', 'char_wailord', 800),
  ('evo_numel_camerupt', 'char_numel', 'char_camerupt', 800),
  ('evo_feebas_milotic', 'char_feebas', 'char_milotic', 1200),
  ('evo_shuppet_banette', 'char_shuppet', 'char_banette', 800),
  ('evo_buizel_floatzel', 'char_buizel', 'char_floatzel', 800),
  ('evo_croagunk_toxicroak', 'char_croagunk', 'char_toxicroak', 800),
  ('evo_gligar_gliscor', 'char_gligar', 'char_gliscor', 800),
  ('evo_murkrow_honchkrow', 'char_murkrow', 'char_honchkrow', 800),
  ('evo_misdreavus_mismagius', 'char_misdreavus', 'char_mismagius', 800),
  ('evo_yanma_yanmega', 'char_yanma', 'char_yanmega', 800),
  ('evo_joltik_galvantula', 'char_joltik', 'char_galvantula', 800),
  ('evo_ferroseed_ferrothorn', 'char_ferroseed', 'char_ferrothorn', 800),
  ('evo_litleo_pyroar', 'char_litleo', 'char_pyroar', 800),
  ('evo_noibat_noivern', 'char_noibat', 'char_noivern', 1000),
  ('evo_mudbray_mudsdale', 'char_mudbray', 'char_mudsdale', 800),
  ('evo_toxel_toxtricity', 'char_toxel', 'char_toxtricity', 800),
  ('evo_cufant_copperajah', 'char_cufant', 'char_copperajah', 800),
  ('evo_charcadet_armarouge', 'char_charcadet', 'char_armarouge', 1000),
  ('evo_fidough_dachsbun', 'char_fidough', 'char_dachsbun', 800),
  ('evo_meltan_melmetal', 'char_meltan', 'char_melmetal', 2000),
  ('evo_seadra_kingdra', 'char_seadra', 'char_kingdra', 1000),
  ('evo_magneton_magnezone', 'char_magneton', 'char_magnezone', 1000),
  ('evo_piloswine_mamoswine', 'char_piloswine', 'char_mamoswine', 1000),
  ('evo_togetic_togekiss', 'char_togetic', 'char_togekiss', 1000);
