-- 63 more characters in 25 evolution lines.
-- * 13 three-stage lines: the Unova starters (Snivy, Tepig, Oshawott), so every
--   generation's starters are now in the game, the baby-led Cleffa, Azurill and Happiny
--   lines, and Pawmi, Fletchling, Vanillite, Hatenna, Impidimp, Flabébé and Scatterbug.
-- * 12 two-stage lines. Gimmighoul and Finizen start at RARE because their final forms
--   are much stronger than the rest, the same as Charcadet.
-- Most picks fill the smallest Pokédex sets: Fairy, Ice, Ghost and Bug.
-- Names and types were checked against PokeAPI. Base forms are sold in the shop and
-- evolved forms are evolution-only (price 0). INSERT OR IGNORE leaves existing rows
-- untouched, and each character has at most one outgoing evolution path.

INSERT OR IGNORE INTO characters (id, external_id, name, slug, type_primary, type_secondary, image_url, price, rarity) VALUES
  ('char_snivy', '495', 'Snivy', 'snivy', 'Grass', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/495.png', 450, 'COMMON'),
  ('char_servine', '496', 'Servine', 'servine', 'Grass', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/496.png', 0, 'RARE'),
  ('char_serperior', '497', 'Serperior', 'serperior', 'Grass', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/497.png', 0, 'EPIC'),
  ('char_tepig', '498', 'Tepig', 'tepig', 'Fire', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/498.png', 450, 'COMMON'),
  ('char_pignite', '499', 'Pignite', 'pignite', 'Fire', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/499.png', 0, 'RARE'),
  ('char_emboar', '500', 'Emboar', 'emboar', 'Fire', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/500.png', 0, 'EPIC'),
  ('char_oshawott', '501', 'Oshawott', 'oshawott', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/501.png', 450, 'COMMON'),
  ('char_dewott', '502', 'Dewott', 'dewott', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/502.png', 0, 'RARE'),
  ('char_samurott', '503', 'Samurott', 'samurott', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/503.png', 0, 'EPIC'),
  ('char_cleffa', '173', 'Cleffa', 'cleffa', 'Fairy', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/173.png', 350, 'COMMON'),
  ('char_clefairy', '35', 'Clefairy', 'clefairy', 'Fairy', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/35.png', 0, 'RARE'),
  ('char_clefable', '36', 'Clefable', 'clefable', 'Fairy', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/36.png', 0, 'EPIC'),
  ('char_azurill', '298', 'Azurill', 'azurill', 'Normal', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/298.png', 350, 'COMMON'),
  ('char_marill', '183', 'Marill', 'marill', 'Water', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/183.png', 0, 'RARE'),
  ('char_azumarill', '184', 'Azumarill', 'azumarill', 'Water', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/184.png', 0, 'EPIC'),
  ('char_happiny', '440', 'Happiny', 'happiny', 'Normal', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/440.png', 400, 'COMMON'),
  ('char_chansey', '113', 'Chansey', 'chansey', 'Normal', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/113.png', 0, 'RARE'),
  ('char_blissey', '242', 'Blissey', 'blissey', 'Normal', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/242.png', 0, 'EPIC'),
  ('char_pawmi', '921', 'Pawmi', 'pawmi', 'Electric', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/921.png', 400, 'COMMON'),
  ('char_pawmo', '922', 'Pawmo', 'pawmo', 'Electric', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/922.png', 0, 'RARE'),
  ('char_pawmot', '923', 'Pawmot', 'pawmot', 'Electric', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/923.png', 0, 'EPIC'),
  ('char_fletchling', '661', 'Fletchling', 'fletchling', 'Normal', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/661.png', 350, 'COMMON'),
  ('char_fletchinder', '662', 'Fletchinder', 'fletchinder', 'Fire', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/662.png', 0, 'RARE'),
  ('char_talonflame', '663', 'Talonflame', 'talonflame', 'Fire', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/663.png', 0, 'EPIC'),
  ('char_vanillite', '582', 'Vanillite', 'vanillite', 'Ice', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/582.png', 350, 'COMMON'),
  ('char_vanillish', '583', 'Vanillish', 'vanillish', 'Ice', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/583.png', 0, 'RARE'),
  ('char_vanilluxe', '584', 'Vanilluxe', 'vanilluxe', 'Ice', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/584.png', 0, 'EPIC'),
  ('char_hatenna', '856', 'Hatenna', 'hatenna', 'Psychic', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/856.png', 400, 'COMMON'),
  ('char_hattrem', '857', 'Hattrem', 'hattrem', 'Psychic', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/857.png', 0, 'RARE'),
  ('char_hatterene', '858', 'Hatterene', 'hatterene', 'Psychic', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/858.png', 0, 'EPIC'),
  ('char_impidimp', '859', 'Impidimp', 'impidimp', 'Dark', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/859.png', 400, 'COMMON'),
  ('char_morgrem', '860', 'Morgrem', 'morgrem', 'Dark', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/860.png', 0, 'RARE'),
  ('char_grimmsnarl', '861', 'Grimmsnarl', 'grimmsnarl', 'Dark', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/861.png', 0, 'EPIC'),
  ('char_flabebe', '669', 'Flabébé', 'flabebe', 'Fairy', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/669.png', 350, 'COMMON'),
  ('char_floette', '670', 'Floette', 'floette', 'Fairy', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/670.png', 0, 'RARE'),
  ('char_florges', '671', 'Florges', 'florges', 'Fairy', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/671.png', 0, 'EPIC'),
  ('char_scatterbug', '664', 'Scatterbug', 'scatterbug', 'Bug', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/664.png', 300, 'COMMON'),
  ('char_spewpa', '665', 'Spewpa', 'spewpa', 'Bug', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/665.png', 0, 'RARE'),
  ('char_vivillon', '666', 'Vivillon', 'vivillon', 'Bug', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/666.png', 0, 'EPIC'),
  ('char_staryu', '120', 'Staryu', 'staryu', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/120.png', 350, 'COMMON'),
  ('char_starmie', '121', 'Starmie', 'starmie', 'Water', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/121.png', 0, 'RARE'),
  ('char_diglett', '50', 'Diglett', 'diglett', 'Ground', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/50.png', 300, 'COMMON'),
  ('char_dugtrio', '51', 'Dugtrio', 'dugtrio', 'Ground', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/51.png', 0, 'RARE'),
  ('char_drifloon', '425', 'Drifloon', 'drifloon', 'Ghost', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/425.png', 350, 'COMMON'),
  ('char_drifblim', '426', 'Drifblim', 'drifblim', 'Ghost', 'Flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/426.png', 0, 'RARE'),
  ('char_sinistea', '854', 'Sinistea', 'sinistea', 'Ghost', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/854.png', 400, 'COMMON'),
  ('char_polteageist', '855', 'Polteageist', 'polteageist', 'Ghost', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/855.png', 0, 'RARE'),
  ('char_gimmighoul', '999', 'Gimmighoul', 'gimmighoul', 'Ghost', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/999.png', 600, 'RARE'),
  ('char_gholdengo', '1000', 'Gholdengo', 'gholdengo', 'Steel', 'Ghost', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1000.png', 0, 'EPIC'),
  ('char_cutiefly', '742', 'Cutiefly', 'cutiefly', 'Bug', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/742.png', 350, 'COMMON'),
  ('char_ribombee', '743', 'Ribombee', 'ribombee', 'Bug', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/743.png', 0, 'RARE'),
  ('char_cubchoo', '613', 'Cubchoo', 'cubchoo', 'Ice', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/613.png', 350, 'COMMON'),
  ('char_beartic', '614', 'Beartic', 'beartic', 'Ice', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/614.png', 0, 'RARE'),
  ('char_snom', '872', 'Snom', 'snom', 'Ice', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/872.png', 350, 'COMMON'),
  ('char_frosmoth', '873', 'Frosmoth', 'frosmoth', 'Ice', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/873.png', 0, 'RARE'),
  ('char_stufful', '759', 'Stufful', 'stufful', 'Normal', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/759.png', 400, 'COMMON'),
  ('char_bewear', '760', 'Bewear', 'bewear', 'Normal', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/760.png', 0, 'RARE'),
  ('char_pancham', '674', 'Pancham', 'pancham', 'Fighting', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/674.png', 400, 'COMMON'),
  ('char_pangoro', '675', 'Pangoro', 'pangoro', 'Fighting', 'Dark', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/675.png', 0, 'RARE'),
  ('char_finizen', '963', 'Finizen', 'finizen', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/963.png', 600, 'RARE'),
  ('char_palafin', '964', 'Palafin', 'palafin', 'Water', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/964.png', 0, 'EPIC'),
  ('char_yamper', '835', 'Yamper', 'yamper', 'Electric', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/835.png', 350, 'COMMON'),
  ('char_boltund', '836', 'Boltund', 'boltund', 'Electric', NULL, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/836.png', 0, 'RARE');

INSERT OR IGNORE INTO evolution_paths (id, from_character_id, to_character_id, point_cost) VALUES
  ('evo_snivy_servine', 'char_snivy', 'char_servine', 600),
  ('evo_servine_serperior', 'char_servine', 'char_serperior', 1000),
  ('evo_tepig_pignite', 'char_tepig', 'char_pignite', 600),
  ('evo_pignite_emboar', 'char_pignite', 'char_emboar', 1000),
  ('evo_oshawott_dewott', 'char_oshawott', 'char_dewott', 600),
  ('evo_dewott_samurott', 'char_dewott', 'char_samurott', 1000),
  ('evo_cleffa_clefairy', 'char_cleffa', 'char_clefairy', 600),
  ('evo_clefairy_clefable', 'char_clefairy', 'char_clefable', 1000),
  ('evo_azurill_marill', 'char_azurill', 'char_marill', 600),
  ('evo_marill_azumarill', 'char_marill', 'char_azumarill', 1000),
  ('evo_happiny_chansey', 'char_happiny', 'char_chansey', 600),
  ('evo_chansey_blissey', 'char_chansey', 'char_blissey', 1000),
  ('evo_pawmi_pawmo', 'char_pawmi', 'char_pawmo', 600),
  ('evo_pawmo_pawmot', 'char_pawmo', 'char_pawmot', 1000),
  ('evo_fletchling_fletchinder', 'char_fletchling', 'char_fletchinder', 600),
  ('evo_fletchinder_talonflame', 'char_fletchinder', 'char_talonflame', 1000),
  ('evo_vanillite_vanillish', 'char_vanillite', 'char_vanillish', 600),
  ('evo_vanillish_vanilluxe', 'char_vanillish', 'char_vanilluxe', 1000),
  ('evo_hatenna_hattrem', 'char_hatenna', 'char_hattrem', 600),
  ('evo_hattrem_hatterene', 'char_hattrem', 'char_hatterene', 1000),
  ('evo_impidimp_morgrem', 'char_impidimp', 'char_morgrem', 600),
  ('evo_morgrem_grimmsnarl', 'char_morgrem', 'char_grimmsnarl', 1000),
  ('evo_flabebe_floette', 'char_flabebe', 'char_floette', 600),
  ('evo_floette_florges', 'char_floette', 'char_florges', 1000),
  ('evo_scatterbug_spewpa', 'char_scatterbug', 'char_spewpa', 600),
  ('evo_spewpa_vivillon', 'char_spewpa', 'char_vivillon', 1000),
  ('evo_staryu_starmie', 'char_staryu', 'char_starmie', 800),
  ('evo_diglett_dugtrio', 'char_diglett', 'char_dugtrio', 800),
  ('evo_drifloon_drifblim', 'char_drifloon', 'char_drifblim', 800),
  ('evo_sinistea_polteageist', 'char_sinistea', 'char_polteageist', 800),
  ('evo_gimmighoul_gholdengo', 'char_gimmighoul', 'char_gholdengo', 1000),
  ('evo_cutiefly_ribombee', 'char_cutiefly', 'char_ribombee', 800),
  ('evo_cubchoo_beartic', 'char_cubchoo', 'char_beartic', 800),
  ('evo_snom_frosmoth', 'char_snom', 'char_frosmoth', 800),
  ('evo_stufful_bewear', 'char_stufful', 'char_bewear', 800),
  ('evo_pancham_pangoro', 'char_pancham', 'char_pangoro', 800),
  ('evo_finizen_palafin', 'char_finizen', 'char_palafin', 1000),
  ('evo_yamper_boltund', 'char_yamper', 'char_boltund', 800);
